/*
 *  EFI Human Interface Infrastructure ... interface
 *
 *  Copyright (c) 2017 Leif Lindholm
 *
 *  SPDX-License-Identifier:     GPL-2.0+
 */

#include <common.h>
#include <efi_loader.h>

const efi_guid_t efi_guid_hii_config_routing_protocol =
	EFI_HII_CONFIG_ROUTING_PROTOCOL_GUID;
const efi_guid_t efi_guid_hii_database_protocol = EFI_HII_DATABASE_PROTOCOL_GUID;
const efi_guid_t efi_guid_hii_string_protocol = EFI_HII_STRING_PROTOCOL_GUID;


/*
 * EFI_HII_CONFIG_ROUTING_PROTOCOL
 */

static efi_status_t extract_config(
	const struct efi_hii_config_routing_protocol *this,
	const efi_string_t request,
	efi_string_t *progress,
	efi_string_t *results)
{
	EFI_ENTRY("%p, \"%ls\", %p, %p", this, request, progress, results);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t export_config(
	const struct efi_hii_config_routing_protocol *this,
	efi_string_t *results)
{
	EFI_ENTRY("%p, %p", this, results);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t route_config(
	const struct efi_hii_config_routing_protocol *this,
	const efi_string_t configuration,
	efi_string_t *progress)
{
	EFI_ENTRY("%p, \"%ls\", %p", this, configuration, progress);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t block_to_config(
	const struct efi_hii_config_routing_protocol *this,
	const efi_string_t config_request,
	const uint8_t *block,
	const UINTN block_size,
	efi_string_t *config,
	efi_string_t *progress)
{
	EFI_ENTRY("%p, \"%ls\", %p, %lu, %p, %p", this, config_request, block,
		  block_size, config, progress);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t config_to_block(
	const struct efi_hii_config_routing_protocol *this,
	const efi_string_t config_resp,
	const uint8_t *block,
	const UINTN *block_size,
	efi_string_t *progress)
{
	EFI_ENTRY("%p, \"%ls\", %p, %p, %p", this, config_resp, block,
		  block_size, progress);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t get_alt_config(
	const struct efi_hii_config_routing_protocol *this,
	const efi_string_t config_resp,
	const efi_guid_t *guid,
	const efi_string_t name,
	const struct efi_device_path *device_path,
	const efi_string_t alt_cfg_id,
	efi_string_t *alt_cfg_resp)
{
	EFI_ENTRY("%p, \"%ls\", %pUl, \"%ls\", %p, \"%ls\", %p", this,
		  config_resp, guid, name, device_path, alt_cfg_id,
		  alt_cfg_resp);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}


/*
 * EFI_HII_DATABASE_PROTOCOL
 */

static efi_status_t new_package_list(
	const struct efi_hii_database_protocol *this,
	const struct efi_hii_package_list_header *package_list,
	const efi_handle_t driver_handle,
	efi_hii_handle_t *handle)
{
	/* Current shell start failure. */
	/* Invoked from MdeModulePkg/Library/UefiHiiLib/HiiLib.c : HiiAddPackages */
	/* (Via autogenerated .c file.) */
	EFI_ENTRY("%p, %p, %p, %p", this, package_list, driver_handle, handle);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t remove_package_list(
	const struct efi_hii_database_protocol *this,
	efi_hii_handle_t handle)
{
	EFI_ENTRY("%p, %p", this, handle);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t update_package_list(
	const struct efi_hii_database_protocol *this,
	efi_hii_handle_t handle,
	const struct efi_hii_package_list_header *package_list)
{
	EFI_ENTRY("%p, %p, %p", this, handle, package_list);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t list_package_lists(
	const struct efi_hii_database_protocol *this,
	uint8_t package_type,
	const efi_guid_t *package_guid,
	UINTN *handle_buffer_length,
	efi_hii_handle_t *handle)
{
	EFI_ENTRY("%p, %u, %pUl, %p, %p", this, package_type, package_guid,
		  handle_buffer_length, handle);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t export_package_lists(
	const struct efi_hii_database_protocol *this,
	efi_hii_handle_t handle,
	UINTN *buffer_size,
	struct efi_hii_package_list_header *buffer)
{
	EFI_ENTRY("%p, %p, %p, %p", this, handle, buffer_size, buffer);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t register_package_notify(
	const struct efi_hii_database_protocol *this,
	uint8_t package_type,
	const efi_guid_t *package_guid,
	const void *package_notify_fn,
	UINTN notify_type,
	efi_handle_t *notify_handle)
{
	EFI_ENTRY("%p, %u, %pUl, %p, %lu, %p", this, package_type,
		  package_guid, package_notify_fn, notify_type,
		  notify_handle);
	return EFI_EXIT(EFI_OUT_OF_RESOURCES);
}

static efi_status_t unregister_package_notify(
	const struct efi_hii_database_protocol *this,
	efi_handle_t notification_handle)
{
	EFI_ENTRY("%p, %p", this, notification_handle);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t find_keyboard_layouts(
	const struct efi_hii_database_protocol *this,
	uint16_t *key_guid_buffer_length,
	efi_guid_t *key_guid_buffer)
{
	EFI_ENTRY("%p, %p, %p", this, key_guid_buffer_length, key_guid_buffer);
	return EFI_EXIT(EFI_NOT_FOUND); /* Invalid */
}

static efi_status_t get_keyboard_layout(
	const struct efi_hii_database_protocol *this,
	efi_guid_t *key_guid,
	uint16_t *keyboard_layout_length,
	struct efi_hii_keyboard_layout *keyboard_layout)
{
	EFI_ENTRY("%p, %pUl, %p, %p", this, key_guid, keyboard_layout_length,
		  keyboard_layout);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t set_keyboard_layout(
	const struct efi_hii_database_protocol *this,
	efi_guid_t *key_guid)
{
	EFI_ENTRY("%p, %pUl", this, key_guid);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t get_package_list_handle(
	const struct efi_hii_database_protocol *this,
	efi_hii_handle_t package_list_handle,
	efi_handle_t *driver_handle)
{
	EFI_ENTRY("%p, %p, %p", this, package_list_handle, driver_handle);
	return EFI_EXIT(EFI_INVALID_PARAMETER);
}


/*
 * EFI_HII_STRING_PROTOCOL
 */

static efi_status_t new_string(
	const struct efi_hii_string_protocol *this,
	efi_hii_handle_t package_list,
	efi_string_id_t *string_id,
	const uint8_t *language,
	const uint16_t *language_name,
	const efi_string_t string,
	const struct efi_font_info *string_font_info)
{
	EFI_ENTRY("%p, %p, %p, %p, %p, \"%ls\", %p", this, package_list,
		  string_id, language, language_name, string,
		  string_font_info);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t get_string(
	const struct efi_hii_string_protocol *this,
	const uint8_t *language,
	efi_hii_handle_t package_list,
	efi_string_id_t string_id,
	efi_string_t string,
	UINTN *string_size,
	struct efi_font_info **string_font_info)
{
	EFI_ENTRY("%p, %p, %p, %u, \"%ls\", %p, %p", this, language,
		  package_list, string_id, string, string_size,
		  string_font_info);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t set_string(
	const struct efi_hii_string_protocol *this,
	efi_hii_handle_t package_list,
	efi_string_id_t string_id,
	const uint8_t *language,
	const efi_string_t string,
	const struct efi_font_info *string_font_info)
{
	EFI_ENTRY("%p, %p, %u, %p, \"%ls\", %p", this, package_list, string_id,
		  language, string, string_font_info);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t get_languages(
	const struct efi_hii_string_protocol *this,
	efi_hii_handle_t package_list,
	uint8_t *languages,
	UINTN *languages_size)
{
	EFI_ENTRY("%p, %p, %p, %p", this, package_list, languages,
		  languages_size);
	return EFI_EXIT(EFI_NOT_FOUND);
}

static efi_status_t get_secondary_languages(
	const struct efi_hii_string_protocol *this,
	efi_hii_handle_t package_list,
	const uint8_t *primary_language,
	uint8_t *secondary_languages,
	UINTN *secondary_languages_size)
{
	EFI_ENTRY("%p, %p, %p, %p, %p", this, package_list, primary_language,
		  secondary_languages, secondary_languages_size);
	return EFI_EXIT(EFI_NOT_FOUND);
}

const struct efi_hii_config_routing_protocol efi_hii_config_routing = {
	.extract_config = extract_config,
	.export_config = export_config,
	.route_config = route_config,
	.block_to_config = block_to_config,
	.config_to_block = config_to_block,
	.get_alt_config = get_alt_config
};
const struct efi_hii_database_protocol efi_hii_database = {
	.new_package_list = new_package_list,
	.remove_package_list = remove_package_list,
	.update_package_list = update_package_list,
	.list_package_lists = list_package_lists,
	.export_package_lists = export_package_lists,
	.register_package_notify = register_package_notify,
	.unregister_package_notify = unregister_package_notify,
	.find_keyboard_layouts = find_keyboard_layouts,
	.get_keyboard_layout = get_keyboard_layout,
	.set_keyboard_layout = set_keyboard_layout,
	.get_package_list_handle = get_package_list_handle
};
const struct efi_hii_string_protocol efi_hii_string = {
	.new_string = new_string,
	.get_string = get_string,
	.set_string = set_string,
	.get_languages = get_languages,
	.get_secondary_languages = get_secondary_languages
};
